version: '3'
services:
  app-scanner:
    build: .
    container_name: app-scanner
    image: oaklabs/app-scanner:latest
    network_mode: host
    stdin_open: true
    tty: true
    devices:
      - /dev/dri
    volumes:
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/shm:/dev/shm
      - /dev/input:/dev/input
    environment:
      - NODE_ENV=production
      - DISPLAY=unix:0.0